databases:
  - name: django_tutorial
    databaseName: django_tutorial
    user: django_tutorial

services:
  - type: web
    name: django_tutorial
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_tutorial.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_tutorial
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4